[build]
command = "pnpm run build"
publish = "dist"

[[headers]]
for = "/*"

[headers.values]
Referrer-Policy = "no-referrer"
Permissions-Policy = ""
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"

[[redirects]]
from = "/index.html"
to = "/"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
