type Map = Record<number, string>;

const day: Map = {
	0: 'i-custom-clear-day',
	1: 'i-custom-partly-cloudy-day',
	2: 'i-custom-partly-cloudy-day',
	3: 'i-custom-overcast-day',
	45: 'i-custom-fog-day',
	48: 'i-custom-fog-day',
	51: 'i-custom-partly-cloudy-day-drizzle',
	53: 'i-custom-drizzle',
	55: 'i-custom-drizzle',
	56: 'i-custom-sleet',
	57: 'i-custom-sleet',
	61: 'i-custom-partly-cloudy-day-rain',
	63: 'i-custom-rain',
	65: 'i-custom-rain',
	66: 'i-custom-sleet',
	67: 'i-custom-sleet',
	71: 'i-custom-partly-cloudy-day-snow',
	73: 'i-custom-snow',
	75: 'i-custom-snow',
	77: 'i-custom-snow',
	80: 'i-custom-partly-cloudy-day-rain',
	81: 'i-custom-rain',
	82: 'i-custom-rain',
	85: 'i-custom-partly-cloudy-day-snow',
	86: 'i-custom-snow',
	95: 'i-custom-thunderstorms-day',
	96: 'i-custom-thunderstorms-day',
	99: 'i-custom-thunderstorms-day',
};

const night: Map = {
	0: 'i-custom-clear-night',
	1: 'i-custom-partly-cloudy-night',
	2: 'i-custom-partly-cloudy-night',
	3: 'i-custom-overcast-night',
	45: 'i-custom-fog-night',
	48: 'i-custom-fog-night',
	51: 'i-custom-partly-cloudy-night-drizzle',
	53: 'i-custom-drizzle',
	55: 'i-custom-drizzle',
	56: 'i-custom-sleet',
	57: 'i-custom-sleet',
	61: 'i-custom-partly-cloudy-night-rain',
	63: 'i-custom-rain',
	65: 'i-custom-rain',
	66: 'i-custom-sleet',
	67: 'i-custom-sleet',
	71: 'i-custom-partly-cloudy-night-snow',
	73: 'i-custom-snow',
	75: 'i-custom-snow',
	77: 'i-custom-snow',
	80: 'i-custom-partly-cloudy-night-rain',
	81: 'i-custom-rain',
	82: 'i-custom-rain',
	85: 'i-custom-partly-cloudy-night-snow',
	86: 'i-custom-snow',
	95: 'i-custom-thunderstorms-night',
	96: 'i-custom-thunderstorms-night',
	99: 'i-custom-thunderstorms-night',
};

export const weatherCodeToIcon = (code: number, isDay: boolean): string | undefined => {
	const map = isDay ? day : night;
	return map[code];
};
